sonar.projectKey=dkg8085_goodparts-react
sonar.organization=dkg8085
sonar.sources=src
sonar.exclusions=**/node_modules/**
# sonar.javascript.lcov.reportPaths=coverage/lcov.info   <-- remove or comment this